# Generated by Django 5.1.7 on 2025-07-06 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('device_type', models.CharField(choices=[('tv', 'TV'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=10)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('target_color', models.CharField(max_length=7)),
                ('short_hint', models.CharField(blank=True, max_length=20)),
                ('long_hint', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.gamesession')),
                ('explainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_explainer', to='core.player')),
            ],
            options={
                'unique_together': {('session', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(choices=[(1, 'Primeira tentativa'), (2, 'Segunda tentativa')])),
                ('chosen_color', models.CharField(max_length=7)),
                ('color_distance', models.FloatField()),
                ('score', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.gameround')),
            ],
            options={
                'unique_together': {('player', 'round', 'attempt_number')},
            },
        ),
    ]
